### PR TITLE
Hot changes

### PR DESCRIPTION
**Pull request by TrySound**
Replaced selector with element
Detect transition with graceful degradation
Add detected transitionProp and transitionEnd to API
Use data-\* attributes instead of dataset
Avoid transition in css

### CODE REVIEW

**Comment by TrySound** [comment]
fix #1

**Comment by TrySound** [comment]
Will be better if you'll give me access.

**Comment by 75lb** [comment]
merged.. and you now have access :+1:

**Comment by TrySound** [comment]
@75lb Cool! Thanks!

**Pull request merged**
